apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
  - path: /metrics
    port: https
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      ca:
        secret:
          name: metrics-server-cert
          key: ca.crt
      serverName: controller-manager-metrics-service.tls-compliance-operator-system.svc
