#!/usr/bin/env bash
# Render plugins/tlsreport.yaml (or --output) with release version and archive SHAs.
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/sebrandon1/tls-compliance-operator}"
OUTPUT=""
VERSION=""
ARCHIVE_DIR=""
declare -A SHA=()
PLATFORMS=(linux-amd64 linux-arm64 darwin-amd64 darwin-arm64)

usage() {
  cat <<'EOF' >&2
Usage:
  generate-krew-manifest.sh --version v1.2.3 \
    --sha-linux-amd64 HEX --sha-linux-arm64 HEX \
    --sha-darwin-amd64 HEX --sha-darwin-arm64 HEX \
    [--output plugins/tlsreport.yaml]

  generate-krew-manifest.sh --version v1.2.3 --archive-dir DIR [--output FILE]
EOF
  exit 1
}

require_value() {
  if [[ $# -lt 2 ]]; then
    echo "error: $1 requires a value" >&2
    usage
  fi
}

file_sha256() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

known_platform() {
  local p=$1
  local x
  for x in "${PLATFORMS[@]}"; do
    if [[ "${x}" == "${p}" ]]; then
      return 0
    fi
  done
  return 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version) require_value "$@"; VERSION=$2; shift 2 ;;
    --archive-dir) require_value "$@"; ARCHIVE_DIR=$2; shift 2 ;;
    --sha-*)
      require_value "$@"
      plat="${1#--sha-}"
      if ! known_platform "${plat}"; then
        echo "error: unknown platform ${plat}" >&2
        usage
      fi
      SHA[$plat]=$2
      shift 2
      ;;
    --output) require_value "$@"; OUTPUT=$2; shift 2 ;;
    -h|--help) usage ;;
    *) echo "unknown argument: $1" >&2; usage ;;
  esac
done

if [[ -n "${ARCHIVE_DIR}" ]]; then
  for p in "${PLATFORMS[@]}"; do
    archive="${ARCHIVE_DIR}/kubectl-tlsreport-${p}.tar.gz"
    if [[ ! -f "${archive}" ]]; then
      echo "error: archive not found: ${archive}" >&2
      exit 1
    fi
    SHA[$p]=$(file_sha256 "${archive}")
  done
fi

missing=0
if [[ -z "${VERSION}" ]]; then
  missing=1
fi
for p in "${PLATFORMS[@]}"; do
  if [[ -z "${SHA[$p]:-}" ]]; then
    missing=1
  fi
done
if [[ "${missing}" -eq 1 ]]; then
  echo "error: --version and all four --sha-* values (or --archive-dir) are required" >&2
  usage
fi

if [[ ! "${VERSION}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+([.-].*)?$ ]]; then
  echo "error: --version must be a v-prefixed semver (got ${VERSION})" >&2
  exit 1
fi

hex='^[0-9a-fA-F]{64}$'
for p in "${PLATFORMS[@]}"; do
  val="${SHA[$p]}"
  if [[ ! "${val}" =~ ${hex} ]]; then
    echo "error: --sha-${p} must be a 64-char hex sha256 (got ${val})" >&2
    exit 1
  fi
done

platforms_yaml=""
for p in "${PLATFORMS[@]}"; do
  os="${p%-*}"
  arch="${p#*-}"
  platforms_yaml+="
  - selector:
      matchLabels:
        os: ${os}
        arch: ${arch}
    uri: ${REPO_URL}/releases/download/${VERSION}/kubectl-tlsreport-${p}.tar.gz
    sha256: ${SHA[$p]}
    bin: kubectl-tlsreport"
done

manifest="# Generated by hack/generate-krew-manifest.sh. Prefer the tlsreport.yaml
# asset on a GitHub release, which is SHA-pinned to that release's archives.
apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: tlsreport
spec:
  version: \"${VERSION}\"
  homepage: ${REPO_URL}
  shortDescription: TLS compliance reports for clusters
  description: |
    Query TLSComplianceReport CRs produced by the TLS Compliance Operator.
    List endpoints, filter by compliance or grade, export CSV/JSON/YAML/JUnit/Markdown,
    and manage TLSComplianceTarget resources.

    Requires the TLS Compliance Operator to be installed in the cluster.
  caveats: |
    The TLS Compliance Operator must be installed and scanning before this plugin
    has reports to show. See ${REPO_URL}#quick-deploy
  platforms:${platforms_yaml}"

if [[ -n "${OUTPUT}" ]]; then
  mkdir -p "$(dirname "${OUTPUT}")"
  printf '%s\n' "${manifest}" > "${OUTPUT}"
else
  printf '%s\n' "${manifest}"
fi
