name: Lint

on:
  push:
    branches: [main]
  pull_request:

permissions: read-all

jobs:
  lint:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Cache golangci-lint
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/golangci-lint
            bin/golangci-lint*
          key: golangci-lint-${{ runner.os }}-${{ hashFiles('Makefile') }}

      - name: Run linter
        run: make lint
